frontend:
  #image: errordeveloper/weave-nats-demo-frontend-js
  build: "./frontend-js"
  ports: [ "0.0.0.0:8080:8080" ]
  hostname: "frontend.weave.local"

bounceme:
  #image: errordeveloper/weave-nats-demo-bounceme-rb
  build: "./bounceme-rb"
